# Generated by Django 5.2.17 on 2026-09-05 15:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('CPU', 'CPU Saturation'), ('MEMORY', 'Memory Exhaustion'), ('DISK', 'Disk Space'), ('SERVICE', 'Service Failure'), ('NETWORK', 'Network Anomaly'), ('SECURITY', 'Security Alert'), ('SYSTEM', 'System Error')], default='SYSTEM', max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('probable_cause', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence percentage 0 - 100%')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('evidence', models.TextField(blank=True, default='', help_text='Detailed diagnostic facts collected.')),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1')),
                ('operating_system', models.CharField(default='Ubuntu 22.04 LTS', max_length=255)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded'), ('CRITICAL', 'Critical')], default='ONLINE', max_length=20)),
                ('is_local', models.BooleanField(default=False, help_text='True if this server corresponds to the local host machine.')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('OPERATOR', 'System Operator'), ('VIEWER', 'Auditor / Viewer')], default='OPERATOR', help_text='Role determining platform permissions.', max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RemediationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=255)),
                ('command_type', models.CharField(help_text='Predefined action identifier, e.g. RESTART_SERVICE, FLUSH_LOGS, DIAGNOSE_PROCESS', max_length=100)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('EXECUTING', 'Executing'), ('SUCCESS', 'Executed Successfully'), ('FAILED', 'Execution Failed'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=50)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, default='', help_text='Standard output / error from safe execution.')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_remediations', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_actions', to='monitoring.incident')),
            ],
            options={
                'verbose_name': 'Remediation Action',
                'verbose_name_plural': 'Remediation Actions',
                'ordering': ['-executed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SSH_BRUTE_FORCE', 'SSH Brute Force Attempt'), ('AUTH_FAILURE', 'Authentication Failure'), ('SUDO_FAILURE', 'Sudo Privilege Abuse'), ('SUSPICIOUS_LOG', 'Suspicious System Log Entry'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt')], default='AUTH_FAILURE', max_length=100)),
                ('source_ip', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='monitoring.server')),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('process_name', models.CharField(max_length=255)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('memory_percent', models.FloatField(default=0.0)),
                ('username', models.CharField(default='root', max_length=100)),
                ('status', models.CharField(default='running', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_metrics', to='monitoring.server')),
            ],
            options={
                'verbose_name': 'Process Metric',
                'verbose_name_plural': 'Process Metrics',
                'ordering': ['-timestamp', '-cpu_percent'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitoring.server'),
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(help_text='Overall CPU percentage (0.0 - 100.0)')),
                ('memory_usage', models.FloatField(help_text='RAM usage percentage (0.0 - 100.0)')),
                ('disk_usage', models.FloatField(help_text='Root partition disk usage percentage (0.0 - 100.0)')),
                ('network_sent', models.BigIntegerField(default=0, help_text='Total bytes sent')),
                ('network_received', models.BigIntegerField(default=0, help_text='Total bytes received')),
                ('load_average', models.CharField(default='0.00, 0.00, 0.00', help_text='System load average (1m, 5m, 15m)', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_metrics', to='monitoring.server')),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (Running)'), ('INACTIVE', 'Inactive (Stopped)'), ('FAILED', 'Failed'), ('NOT_FOUND', 'Not Installed / Not Found')], default='NOT_FOUND', max_length=50)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_statuses', to='monitoring.server')),
            ],
            options={
                'verbose_name': 'Service Status',
                'verbose_name_plural': 'Service Statuses',
                'ordering': ['service_name'],
                'unique_together': {('server', 'service_name')},
            },
        ),
    ]
