# Generated by Django 5.2.17 on 2026-09-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='kernel_version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
